In [2]:
import pandas as pd
import numpy as np

In [3]:
data= {
   "Employee_ID": [101,102,103,104,105,106,107,108],
   "Name": ["Amit","Priya","Rahul","Sneha","Vikram","Anjali","Karan","Meera"],
   "Department": ["HR","IT","IT","Finance","HR","Finance","IT","HR"],
   "Age": [25,30,28,35,40,29,32,26],
   "Experience_Years": [2,5,3,10,15,4,6,1],
   "Salary": [30000,50000,45000,70000,90000,48000,52000,28000],
   "Joining_Date": ["2020-01-15","2018-07-10","2019-03-25","2015-11-01",
                    "2010-06-17","2021-09-12","2017-04-19","2022-02-01"],
   "Performance_Score": [3.5,4.2,4.0,4.8,3.9,4.1,4.3,3.6]
}

df = pd.DataFrame(data)

In [4]:
df

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
0,101,Amit,HR,25,2,30000,2020-01-15,3.5
1,102,Priya,IT,30,5,50000,2018-07-10,4.2
2,103,Rahul,IT,28,3,45000,2019-03-25,4.0
3,104,Sneha,Finance,35,10,70000,2015-11-01,4.8
4,105,Vikram,HR,40,15,90000,2010-06-17,3.9
5,106,Anjali,Finance,29,4,48000,2021-09-12,4.1
6,107,Karan,IT,32,6,52000,2017-04-19,4.3
7,108,Meera,HR,26,1,28000,2022-02-01,3.6

## Basic Understanding Attributes

In [5]:
df.size

64

In [6]:
df.shape

(8, 8)

In [7]:
df.ndim

2

In [10]:
df.index

RangeIndex(start=0, stop=8, step=1)

In [11]:
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Age', 'Experience_Years',
       'Salary', 'Joining_Date', 'Performance_Score'],
      dtype='object')

Display the first 5 rows of the dataset.

In [12]:
df.head()

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
0,101,Amit,HR,25,2,30000,2020-01-15,3.5
1,102,Priya,IT,30,5,50000,2018-07-10,4.2
2,103,Rahul,IT,28,3,45000,2019-03-25,4.0
3,104,Sneha,Finance,35,10,70000,2015-11-01,4.8
4,105,Vikram,HR,40,15,90000,2010-06-17,3.9

Display the last 3 rows.

In [14]:
df.tail(3)

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
5,106,Anjali,Finance,29,4,48000,2021-09-12,4.1
6,107,Karan,IT,32,6,52000,2017-04-19,4.3
7,108,Meera,HR,26,1,28000,2022-02-01,3.6

Find the shape of the dataset.

In [15]:
df.shape

(8, 8)

Display all column names.

In [16]:
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Age', 'Experience_Years',
       'Salary', 'Joining_Date', 'Performance_Score'],
      dtype='object')

Check the data types of each column

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        8 non-null      int64
 1   Name               8 non-null      object
 2   Department         8 non-null      object
 3   Age                8 non-null      int64
 4   Experience_Years   8 non-null      int64
 5   Salary             8 non-null      int64
 6   Joining_Date       8 non-null      object
 7   Performance_Score  8 non-null      float64
dtypes: float64(1), int64(4), object(3)
memory usage: 644.0+ bytes

Find the number of rows and columns separately.

In [20]:
df.shape[0]

8

In [21]:
df.shape[1]

8

Check the memory usage of the dataset.

In [22]:
df.info(memory_usage="Deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        8 non-null      int64
 1   Name               8 non-null      object
 2   Department         8 non-null      object
 3   Age                8 non-null      int64
 4   Experience_Years   8 non-null      int64
 5   Salary             8 non-null      int64
 6   Joining_Date       8 non-null      object
 7   Performance_Score  8 non-null      float64
dtypes: float64(1), int64(4), object(3)
memory usage: 644.0+ bytes

In [25]:
df.memory_usage(deep=True)

Index                132
Employee_ID           64
Name                 433
Department           418
Age                   64
Experience_Years      64
Salary                64
Joining_Date         472
Performance_Score     64
dtype: int64

In [26]:
df.memory_usage(deep=True).sum()

np.int64(1775)

In [27]:
df

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
0,101,Amit,HR,25,2,30000,2020-01-15,3.5
1,102,Priya,IT,30,5,50000,2018-07-10,4.2
2,103,Rahul,IT,28,3,45000,2019-03-25,4.0
3,104,Sneha,Finance,35,10,70000,2015-11-01,4.8
4,105,Vikram,HR,40,15,90000,2010-06-17,3.9
5,106,Anjali,Finance,29,4,48000,2021-09-12,4.1
6,107,Karan,IT,32,6,52000,2017-04-19,4.3
7,108,Meera,HR,26,1,28000,2022-02-01,3.6

Convert Joining_Date column to datetime and verify the change.

In [28]:
df["Joining_Date"]=pd.to_datetime(df["Joining_Date"])

In [29]:
df

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
0,101,Amit,HR,25,2,30000,2020-01-15,3.5
1,102,Priya,IT,30,5,50000,2018-07-10,4.2
2,103,Rahul,IT,28,3,45000,2019-03-25,4.0
3,104,Sneha,Finance,35,10,70000,2015-11-01,4.8
4,105,Vikram,HR,40,15,90000,2010-06-17,3.9
5,106,Anjali,Finance,29,4,48000,2021-09-12,4.1
6,107,Karan,IT,32,6,52000,2017-04-19,4.3
7,108,Meera,HR,26,1,28000,2022-02-01,3.6

## Methods to Understand Data

Use .info() and explain what information it provides.

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        8 non-null      int64
 1   Name               8 non-null      object
 2   Department         8 non-null      object
 3   Age                8 non-null      int64
 4   Experience_Years   8 non-null      int64
 5   Salary             8 non-null      int64
 6   Joining_Date       8 non-null      datetime64[ns]
 7   Performance_Score  8 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(4), object(2)
memory usage: 644.0+ bytes

Use .describe() for numerical columns. What insights can you observe?

In [32]:
df.describe()

,Employee_ID,Age,Experience_Years,Salary,Joining_Date,Performance_Score
count,8.00000,8.000000,8.000000,8.00000,8,8.000000
mean,104.50000,30.625000,5.750000,51625.00000,2018-02-22 12:00:00,4.050000
min,101.00000,25.000000,1.000000,28000.00000,2010-06-17 00:00:00,3.500000
25%,102.75000,27.500000,2.750000,41250.00000,2016-12-06 06:00:00,3.825000
50%,104.50000,29.500000,4.500000,49000.00000,2018-11-16 00:00:00,4.050000
75%,106.25000,32.750000,7.000000,56500.00000,2020-06-14 12:00:00,4.225000
max,108.00000,40.000000,15.000000,90000.00000,2022-02-01 00:00:00,4.800000
std,2.44949,4.955156,4.652188,20339.52872,NaN,0.410575

Use .describe(include='object') to summarize categorical columns.

In [34]:
df.describe(include="object")

        Name Department
count      8          8
unique     8          3
top     Amit         HR
freq       1          3

Check for missing values in the dataset.

In [35]:
df.isnull()

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False

In [38]:
df.isna()

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False

In [40]:
df.isna().sum()

Employee_ID          0
Name                 0
Department           0
Age                  0
Experience_Years     0
Salary               0
Joining_Date         0
Performance_Score    0
dtype: int64

Count the number of unique values in each column.

In [42]:
df.nunique()

Employee_ID          8
Name                 8
Department           3
Age                  8
Experience_Years     8
Salary               8
Joining_Date         8
Performance_Score    8
dtype: int64

Display frequency count of employees in each department.

In [43]:
df

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
0,101,Amit,HR,25,2,30000,2020-01-15,3.5
1,102,Priya,IT,30,5,50000,2018-07-10,4.2
2,103,Rahul,IT,28,3,45000,2019-03-25,4.0
3,104,Sneha,Finance,35,10,70000,2015-11-01,4.8
4,105,Vikram,HR,40,15,90000,2010-06-17,3.9
5,106,Anjali,Finance,29,4,48000,2021-09-12,4.1
6,107,Karan,IT,32,6,52000,2017-04-19,4.3
7,108,Meera,HR,26,1,28000,2022-02-01,3.6

In [44]:
df_counts=df["Department"].value_counts()

In [45]:
df_counts

Department
HR         3
IT         3
Finance    2
Name: count, dtype: int64

## Filtering & Logical Thinking

Display employees whose salary is greater than 50,000.

In [46]:
df

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
0,101,Amit,HR,25,2,30000,2020-01-15,3.5
1,102,Priya,IT,30,5,50000,2018-07-10,4.2
2,103,Rahul,IT,28,3,45000,2019-03-25,4.0
3,104,Sneha,Finance,35,10,70000,2015-11-01,4.8
4,105,Vikram,HR,40,15,90000,2010-06-17,3.9
5,106,Anjali,Finance,29,4,48000,2021-09-12,4.1
6,107,Karan,IT,32,6,52000,2017-04-19,4.3
7,108,Meera,HR,26,1,28000,2022-02-01,3.6

In [47]:
df[df["Salary"]>50000]

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
3,104,Sneha,Finance,35,10,70000,2015-11-01,4.8
4,105,Vikram,HR,40,15,90000,2010-06-17,3.9
6,107,Karan,IT,32,6,52000,2017-04-19,4.3

Display employees who belong to the IT department and have experience more than 4 years

In [54]:
result=df[(df["Department"]=="IT")&(df["Experience_Years"]>4)]

In [55]:
result

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
1,102,Priya,IT,30,5,50000,2018-07-10,4.2
6,107,Karan,IT,32,6,52000,2017-04-19,4.3

Find the average salary department-wise.

In [56]:
df.groupby("Department")["Salary"].mean()

Department
Finance    59000.000000
HR         49333.333333
IT         49000.000000
Name: Salary, dtype: float64

Find the employee with the highest salary.

In [60]:
highest_salary=df.nlargest(1,"Salary")

In [61]:
highest_salary

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
4,105,Vikram,HR,40,15,90000,2010-06-17,3.9

Find employees whose performance score is above the overall average performance score.

In [63]:
df

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
0,101,Amit,HR,25,2,30000,2020-01-15,3.5
1,102,Priya,IT,30,5,50000,2018-07-10,4.2
2,103,Rahul,IT,28,3,45000,2019-03-25,4.0
3,104,Sneha,Finance,35,10,70000,2015-11-01,4.8
4,105,Vikram,HR,40,15,90000,2010-06-17,3.9
5,106,Anjali,Finance,29,4,48000,2021-09-12,4.1
6,107,Karan,IT,32,6,52000,2017-04-19,4.3
7,108,Meera,HR,26,1,28000,2022-02-01,3.6

In [65]:
average=df["Performance_Score"].mean()

In [67]:
average

np.float64(4.05)

In [69]:
df[df["Performance_Score"]>average]

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score
1,102,Priya,IT,30,5,50000,2018-07-10,4.2
3,104,Sneha,Finance,35,10,70000,2015-11-01,4.8
5,106,Anjali,Finance,29,4,48000,2021-09-12,4.1
6,107,Karan,IT,32,6,52000,2017-04-19,4.3

Create a new column called Salary_Per_Experience and analyze which employee is getting paid the most per year of experience.

In [70]:
df["Salary_Per_Experience"] = df["Salary"] / df["Experience_Years"]

top_employee = df.loc[df["Salary_Per_Experience"].idxmax()]

In [71]:
top_employee

Employee_ID                              108
Name                                   Meera
Department                                HR
Age                                       26
Experience_Years                           1
Salary                                 28000
Joining_Date             2022-02-01 00:00:00
Performance_Score                        3.6
Salary_Per_Experience                28000.0
Name: 7, dtype: object

In [72]:
df

,Employee_ID,Name,Department,Age,Experience_Years,Salary,Joining_Date,Performance_Score,Salary_Per_Experience
0,101,Amit,HR,25,2,30000,2020-01-15,3.5,15000.000000
1,102,Priya,IT,30,5,50000,2018-07-10,4.2,10000.000000
2,103,Rahul,IT,28,3,45000,2019-03-25,4.0,15000.000000
3,104,Sneha,Finance,35,10,70000,2015-11-01,4.8,7000.000000
4,105,Vikram,HR,40,15,90000,2010-06-17,3.9,6000.000000
5,106,Anjali,Finance,29,4,48000,2021-09-12,4.1,12000.000000
6,107,Karan,IT,32,6,52000,2017-04-19,4.3,8666.666667
7,108,Meera,HR,26,1,28000,2022-02-01,3.6,28000.000000