## Pandas-Duplicates,Missing,Outliers.

Handling Duplicates

## Question 1

In [1]:
data = {
'Product': ['Laptop', 'Mouse', 'Keyboard', 'Mouse', 'Laptop'],
'Price': [50000, 500, 1500, 500, 50000]
}

In [3]:
import pandas as pd

In [5]:
df=pd.DataFrame(data)
df

    Product  Price
0    Laptop  50000
1     Mouse    500
2  Keyboard   1500
3     Mouse    500
4    Laptop  50000

##  identify the duplicate rows

In [22]:

df[df.duplicated()]

  Product  Price
3   Mouse    500
4  Laptop  50000

# Display duplicate rows

In [28]:

df[df.duplicated(subset=["Product"],keep="first")]

  Product  Price
3   Mouse    500
4  Laptop  50000

## Question 2

In [29]:
data = {
'Student': ['A', 'B', 'C', 'A', 'D'],
'Marks': [80, 75, 90, 80, 85]
}

In [31]:
df=pd.DataFrame(data)
df

  Student  Marks
0       A     80
1       B     75
2       C     90
3       A     80
4       D     85

Identify duplicate student records.

In [33]:
df[df.duplicated()]

  Student  Marks
3       A     80

Display duplicate rows.

In [35]:
df[df.duplicated(keep=False)]

  Student  Marks
0       A     80
3       A     80

Remove duplicates.

In [38]:
df.drop_duplicates(keep=False,ignore_index=False)

  Student  Marks
1       B     75
2       C     90
4       D     85

## Question 3

In [41]:
data = {
'City': ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Mumbai'],
'Population': [19, 20, 19, 10, 20]
}
df=pd.DataFrame(data)
df

      City  Population
0    Delhi          19
1   Mumbai          20
2    Delhi          19
3  Chennai          10
4   Mumbai          20

find duplicate rows

In [43]:
df[df.duplicated(keep=False)]

     City  Population
0   Delhi          19
1  Mumbai          20
2   Delhi          19
4  Mumbai          20

Count the number of duplicate rows

In [48]:
print(df.duplicated().sum())

2

### Question 4

In [49]:
data = {
'EmployeeID': [101, 102, 103, 101, 104],
'Department': ['HR', 'IT', 'Finance', 'HR', 'IT']
}
df=pd.DataFrame(data)
df

   EmployeeID Department
0         101         HR
1         102         IT
2         103    Finance
3         101         HR
4         104         IT

Detect duplicate Employee IDs.

In [51]:
df[df.duplicated(subset="EmployeeID")]

   EmployeeID Department
3         101         HR

Display duplicate records.

In [55]:
df[df.duplicated(keep=False)]

   EmployeeID Department
0         101         HR
3         101         HR

### Question 5

In [57]:
data = {
'OrderID': [1, 2, 3, 3, 4],
'Amount': [200, 150, 300, 300, 250]
}
df=pd.DataFrame(data)
df

   OrderID  Amount
0        1     200
1        2     150
2        3     300
3        3     300
4        4     250

Identify duplicate orders.

In [59]:
df[df.duplicated(subset="OrderID",keep=False)]

   OrderID  Amount
2        3     300
3        3     300

Remove duplicate rows.

In [62]:
df.drop_duplicates(keep="first")

   OrderID  Amount
0        1     200
1        2     150
2        3     300
4        4     250

# Section 2: Handling Missing Values

### Question 1

In [87]:
data = {
'Name': ['Amit', 'Priya', 'Rahul', 'Sneha'],
'Salary': [50000, None, 45000, None]
}
df=pd.DataFrame(data)
df

    Name   Salary
0   Amit  50000.0
1  Priya      NaN
2  Rahul  45000.0
3  Sneha      NaN

Identify missing values.

In [88]:
df[df['Salary'].isnull()]

    Name  Salary
1  Priya     NaN
3  Sneha     NaN


Count missing values.

In [89]:
print(df["Salary"].isnull().sum())

2

Fill missing values with mean salary.

In [91]:
missing_salary=df["Salary"].mean()

In [92]:
df["Salary"]=df["Salary"].fillna(missing_salary)

In [93]:
print(df)

    Name   Salary
0   Amit  50000.0
1  Priya  47500.0
2  Rahul  45000.0
3  Sneha  47500.0

## Question 2

In [99]:
data = {
'Student': ['A', 'B', 'C', 'D'],
'Marks': [85, None, 78, 92]
}
df=pd.DataFrame(data)
df

  Student  Marks
0       A   85.0
1       B    NaN
2       C   78.0
3       D   92.0

Identify missing values.

In [100]:
df["Marks"].isnull().sum()

np.int64(1)

Fill missing values with median.

In [101]:
df["Marks"]=df["Marks"].fillna(df["Marks"].mean())

In [102]:
df

  Student  Marks
0       A   85.0
1       B   85.0
2       C   78.0
3       D   92.0

## Question 3

In [103]:
data = {
'City': ['Delhi', 'Mumbai', 'Chennai', 'Kolkata'],
'Temperature': [32, None, 30, None]
}
df=pd.DataFrame(data)
df

      City  Temperature
0    Delhi         32.0
1   Mumbai          NaN
2  Chennai         30.0
3  Kolkata          NaN

Identify missing values.

In [104]:
df.isnull()

    City  Temperature
0  False        False
1  False         True
2  False        False
3  False         True

Replace missing values with the average temperature.

In [105]:
df["Temperature"]=df["Temperature"].fillna(df["Temperature"].mean())

In [106]:
df

      City  Temperature
0    Delhi         32.0
1   Mumbai         31.0
2  Chennai         30.0
3  Kolkata         31.0

## Question 4

In [108]:
data = {
'Product': ['A', 'B', 'C', 'D'],
'Stock': [20, None, 15, None]
}
df=pd.DataFrame(data)
df

  Product  Stock
0       A   20.0
1       B    NaN
2       C   15.0
3       D    NaN

In [109]:
df.isnull()

   Product  Stock
0    False  False
1    False   True
2    False  False
3    False   True

In [110]:
df["Stoct"]=df["Stock"].fillna(df["Stock"].ffill())

In [111]:
df

  Product  Stock  Stoct
0       A   20.0   20.0
1       B    NaN   20.0
2       C   15.0   15.0
3       D    NaN   15.0

## Question 5

In [112]:
data = {
'Employee': ['E1', 'E2', 'E3', 'E4'],
'Experience': [2, None, 4, None]
}
df=pd.DataFrame(data)
df

  Employee  Experience
0       E1         2.0
1       E2         NaN
2       E3         4.0
3       E4         NaN

In [113]:
df.isnull()

   Employee  Experience
0     False       False
1     False        True
2     False       False
3     False        True

In [114]:
df.dropna()

  Employee  Experience
0       E1         2.0
2       E3         4.0

## Handling Outliers

In [120]:
data = {
'Sales': [200, 220, 250, 240, 260, 1000]
}
df=pd.DataFrame(data)
df

   Sales
0    200
1    220
2    250
3    240
4    260
5   1000

In [121]:
Q1=df["Sales"].quantile(0.25)
Q2=df["Sales"].quantile(0.5)
Q3=df["Sales"].quantile(0.75)

In [124]:
IQR=Q3-Q1

In [125]:
IQR

np.float64(32.5)

In [126]:
lower_boundary=Q1-1.5*IQR
Higher_boundary=Q3+1.5*IQR

In [127]:
result=df[(df["Sales"]<lower_boundary)|(df["Sales"]>Higher_boundary)]

In [128]:
result

   Sales
5   1000

In [189]:
data = {
'Price': [100, 120, 115, 110, 900]
}
df=pd.DataFrame(data)
print(df)

   Price
0    100
1    120
2    115
3    110
4    900

In [190]:
Q1=df["Price"].quantile(0.25)
Q2=df["Price"].quantile(0.5)
Q3=df["Price"].quantile(0.75)

In [191]:
IQR=Q3-Q1

In [192]:
lower_boundary=Q1-1.5*IQR
higher_boundary=Q3+1.5*IQR
print(lower_boundary)
print(higher_boundary)

95.0
135.0

In [193]:
outliyer=df[(df["Price"]<lower_boundary)|(df["Price"]>higher_boundary)]

In [194]:
outliyer

   Price
4    900

In [195]:
df[df["Price"]==900]

   Price
4    900

In [196]:
data = {
'Temperature': [30, 31, 29, 32, 100]
}
df=pd.DataFrame(data)
df

   Temperature
0           30
1           31
2           29
3           32
4          100

In [197]:
Q1=df["Temperature"].quantile(0.25)
Q2=df["Temperature"].quantile(0.5)
Q3=df["Temperature"].quantile(0.75)

In [198]:
IQR=Q3-Q1

In [199]:
lower_boundary=Q1-1.5*IQR
higher_boundary=Q3+1.5*IQR

In [202]:
outliyer_detect=df[(df["Temperature"]<lower_boundary)|(df["Temperature"]>higher_boundary)]

In [203]:
outliyer_detect

   Temperature
4          100

In [204]:
remove_outliyer=df[(df["Temperature"]>lower_boundary)&(df["Temperature"]<higher_boundary)]

In [205]:
remove_outliyer

   Temperature
0           30
1           31
2           29
3           32

In [207]:
data = {
'Quantity': [10, 12, 11, 13, 50]
}
df=pd.DataFrame(data)
df

   Quantity
0        10
1        12
2        11
3        13
4        50

In [208]:
q1=df["Quantity"].quantile(0.25)
q3=df["Quantity"].quantile(0.75)

In [209]:
IQR=q1-q3

In [210]:
lower_boundary=q1-1.5*IQR
higher_boundary=q3+1.5*IQR

In [217]:
outliers = df[(df['Quantity'] < lower_boundary) | (df['Quantity'] > higher_boundary)]
outlier

   Temperature
4          100

In [220]:
median_value=df["Quantity"].median()

In [221]:
df["Quantity"]=df["Quantity"].apply(lambda x:median_value if(x<lower_boundary or x>higher_boundary)else x)

In [224]:
df["Quantity"]

0    12.0
1    12.0
2    12.0
3    12.0
4    12.0
Name: Quantity, dtype: float64

In [225]:
data = {
'Score': [70, 75, 80, 85, 95, 40]
}
df=pd.DataFrame(data)
df

   Score
0     70
1     75
2     80
3     85
4     95
5     40

In [227]:
Q1=df["Score"].quantile(0.25)
Q3=df["Score"].quantile(0.75)

In [228]:
IQR=Q3-Q1

In [229]:
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

In [230]:
outlier=df[(df["Score"]<lower)|(df["Score"]>upper)]

In [231]:
outlier

   Score
5     40