## Pandas_Series_DataFrame_creation
- A.Pandas Series

In [1]:
import pandas as pd

In [2]:
temps=pd.Series( [12, 3, 4, 4, 5])
temps

0    12
1     3
2     4
3     4
4     5
dtype: int64

Create a Pandas Series from the following tuple of employee names:

 employees = ("Amit", "Neha", "Raj", "Sara")

In [3]:
employee=pd.Series(["Amit","Neha","Raj","Sara"])
print(employee)

0    Amit
1    Neha
2     Raj
3    Sara
dtype: object

Create a Pandas Series from the following set of unique product IDs:

 product_ids = {101, 102, 103, 104}

In [4]:
product_Ids=pd.Series(list({101,102,103,104}))
product_Ids

0    104
1    101
2    102
3    103
dtype: int64

Create a Pandas Series from the following dictionary where keys are subjects and values are marks:

 marks = {
    "Math": 85,
    "Science": 90,
    "English": 88
}

In [5]:
marks={"Maths":85,"Science":90,"English":88}
df=pd.Series(marks)
df

Maths      85
Science    90
English    88
dtype: int64

Create a Pandas Series from the following NumPy array of monthly expenses:

- import numpy as np
- expenses = np.array([12000, 15000, 11000, 18000])

In [6]:
import numpy as np

In [7]:
expenes=np.array([12000,15000,11000,18000])
df=pd.Series(expenes)
print(df)

0    12000
1    15000
2    11000
3    18000
dtype: int64

Print the index and values of the Series created from temps.

In [8]:
pd.Series(temps)

0    12
1     3
2     4
3     4
4     5
dtype: int64

In [9]:
print("Temps",temps.index)
print("Values",temps.values)

Temps RangeIndex(start=0, stop=5, step=1)
Values [12  3  4  4  5]

Print the index and values of the Series created from employees.

In [10]:

print("Index fromm employees:",employee.index)
print("values from employees:",employee.values)

Index fromm employees: RangeIndex(start=0, stop=4, step=1)
values from employees: ['Amit' 'Neha' 'Raj' 'Sara']

Print the index and values of the Series created from marks.

In [11]:
print("Index from marks:",df.index)
print("values from marks:",df.values)

Index from marks: RangeIndex(start=0, stop=4, step=1)
values from marks: [12000 15000 11000 18000]

Create a Series using the following list and manually assign custom index labels:
scores = [70, 80, 90]

In [12]:
scores=[70,80,90]

In [13]:
scores=pd.Series(scores,index=["Maths","Science","Telugu"])
scores

Maths      70
Science    80
Telugu     90
dtype: int64

Create a Series from the dictionary marks and display only its values.

In [14]:
series={"Maths":85,"Science":90,"English":88}
marks=pd.Series(series)
print(series.values())

dict_values([85, 90, 88])

Create a Pandas Series from the following NumPy array of monthly expenses:

- import numpy as np
- expenses = np.array([12000, 15000, 11000, 18000])

In [15]:
import numpy as np
import pandas as pd

In [16]:
expenses = np.array([12000, 15000, 11000, 18000])

In [17]:
df=pd.Series(expenses)
print(df)

0    12000
1    15000
2    11000
3    18000
dtype: int64

Print the index and values of the Series created from temps.

In [18]:
print("index from temps:",temps.index)
print("values from temps:",temps.values)

index from temps: RangeIndex(start=0, stop=5, step=1)
values from temps: [12  3  4  4  5]

Print the index and values of the Series created from employees.

In [19]:
print("employee index:",employee.index)
print("employee values:",employee.values)

employee index: RangeIndex(start=0, stop=4, step=1)
employee values: ['Amit' 'Neha' 'Raj' 'Sara']

Print the index and values of the Series created from marks.

In [20]:
print("index from marks:",marks.index)
print('values from marks:',marks.values)

index from marks: Index(['Maths', 'Science', 'English'], dtype='object')
values from marks: [85 90 88]

Create a Series using the following list and manually assign custom index labels:
- scores = [70, 80, 90]
- Custom index:
- ["Test1", "Test2", "Test3"]

In [21]:
scoress=[70,80,90]
df=pd.Series(scoress,index=["Test1","Test2","Test3"])
print(df)

Test1    70
Test2    80
Test3    90
dtype: int64

Create a Series from the dictionary marks and display only its values.

In [22]:
dictionary={"Maths":85,"Science":90,"English":88}
df=pd.Series(dictionary)
print(df.values)

[85 90 88]

Convert the following list of Boolean values into a Pandas Series:
flags = [True, False, True, True]

In [23]:
flags = [True, False, True, True]
series = pd.Series(flags)

print(series)

0     True
1    False
2     True
3     True
dtype: bool

Create a Series from the NumPy array expenses and check its data type.

print(type(expenses))

## B.Pandas DataFrame

Create a Pandas DataFrame from the following list of lists representing student ID, name, and score:

 - Students = [
    [1, "Rahul", 85],
    [2, "Sneha", 92],
    [3, "Arjun", 78]
]

In [24]:
data={"ID":[1,2,3],
    "Students" : ["Rahul", "Sneha" ,"Arjun"],
"Score":[85,92,78]}

In [25]:
df=pd.DataFrame(data)
df

   ID Students  Score
0   1    Rahul     85
1   2    Sneha     92
2   3    Arjun     78

Create a Pandas DataFrame from the following dictionary of lists:

 - products = {
  -   "Product": ["Pen", "Book", "Pencil"],
   -  "Price": [10, 50, 5],
   -  "Quantity": [100, 40, 200]
}

In [26]:
data={"Product":["Pen","Book","Pencil"],
     "Price":[10,50,5],
     "Quantity":[100,40,200]}

In [27]:
df=pd.DataFrame(data)
df

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        40
2  Pencil      5       200

Create a Pandas DataFrame from the following NumPy array representing employee data:

 emp_data = np.array([
    [101, "John", 50000],
    [102, "Alice", 60000],
    [103, "Bob", 55000]
])

In [28]:
emp_data = np.array([
    [101, "John", 50000],
    [102, "Alice", 60000],
    [103, "Bob", 55000]
])
df=pd.DataFrame(emp_data)
df

     0      1      2
0  101   John  50000
1  102  Alice  60000
2  103    Bob  55000

In [29]:
df.columns=[["Emp_Id","Name","Salary"]]

In [30]:
df

  Emp_Id   Name Salary
0    101   John  50000
1    102  Alice  60000
2    103    Bob  55000

Assign column names ["ID", "Name", "Score"] to the students DataFrame.

In [31]:
data={"ID":[1,2,3],
    "Students" : ["Rahul", "Sneha" ,"Arjun"],
"Score":[85,92,78]}
df=pd.DataFrame(data)
df

   ID Students  Score
0   1    Rahul     85
1   2    Sneha     92
2   3    Arjun     78

Assign column names ["EmpID", "EmpName", "Salary"] to the employee DataFrame.

In [32]:
df.columns=[["Emp_Id","Name",
             "Salary"]]

In [33]:
df

  Emp_Id   Name Salary
0      1  Rahul     85
1      2  Sneha     92
2      3  Arjun     78

## C.Observation & Generalization Questions

Given Data

- marks = [1, 2, 43, 4]
- expenses = [12000, 15000, 11000, 18000]

 Convert the Series created from marks into a DataFrame.
- First, create a Series using marks.
- Then convert that Series into a DataFrame

In [34]:
import pandas as pd
import numpy as np

In [35]:
marks = [1, 2, 43, 4]
df=pd.Series(marks)
df=pd.DataFrame(df)
df

    0
0   1
1   2
2  43
3   4

Convert the Series created from expenses into a DataFrame.
- First, create a Series using expenses.
- Then convert that Series into a DataFrame.

In [36]:
expenses = [12000, 15000, 11000, 18000]
df1=pd.Series(expenses)
result=pd.DataFrame(df1)
result

       0
0  12000
1  15000
2  11000
3  18000

Print the index and column names after converting the Series (from      marks) into a DataFrame.
Use appropriate attributes to display:
Index


Column names

In [37]:
marks = [1, 2, 43, 4]
df=pd.Series(marks)
df=pd.DataFrame(df)
df

    0
0   1
1   2
2  43
3   4

In [38]:
df.columns=["Marks"]

In [39]:
df

   Marks
0      1
1      2
2     43
3      4

In [41]:
print("index of marks:",df.index)
print("Column names:",df.columns)

index of marks: RangeIndex(start=0, stop=4, step=1)
Column names: Index(['Marks'], dtype='object')

 4. Identify the number of rows and columns in the DataFrame converted    from marks.
Use the appropriate attribute to determine:
Number of rows


Number of columns

In [44]:
df.shape

(4, 1)

In [47]:
rows,cols=df.shape

In [48]:
print("Rows:",rows)
print("columns:",cols)

Rows: 4
columns: 1

   5. Create any Series and check its type.
Create a Series using any list and check the type of the object.

In [50]:
df=pd.Series([1,3,4,5,6,78])
df.dtype

dtype('int64')