## pandas Merge

In [1]:
import pandas as pd

In [2]:
df_students = pd.DataFrame({
    "Student_ID": [1, 2, 3, 4],
    "Name": ["Amit", "Ravi", "Sita", "Neha"]
})

df_marks = pd.DataFrame({
    "Student_ID": [2, 3, 4, 5],
    "Marks": [85, 90, 75, 60]
})

df_courses = pd.DataFrame({
    "Student_ID": [1, 2, 3],
    "Course": ["Math", "Science", "English"]
})

1. Perform an inner merge between df_students and df_marks ( INNER JOIN) and display the result.

In [4]:
pd.merge(df_students,df_marks,on="Student_ID",how="inner")

   Student_ID  Name  Marks
0           2  Ravi     85
1           3  Sita     90
2           4  Neha     75

2. Perform a left merge between df_students and df_marks(LEFT JOIN) and display the result.

In [6]:
df=pd.merge(df_students,df_marks,on="Student_ID",how="left")
df

   Student_ID  Name  Marks
0           1  Amit    NaN
1           2  Ravi   85.0
2           3  Sita   90.0
3           4  Neha   75.0

3. Perform a right merge between df_students and df_marks(RIGHT JOIN) and display the result.

In [8]:
pd.merge(df_students, df_marks, on="Student_ID", how="right")

   Student_ID  Name  Marks
0           2  Ravi     85
1           3  Sita     90
2           4  Neha     75
3           5   NaN     60

4. Perform a full outer merge between df_students and df_marks( OUTER JOIN) and display the result.

In [10]:
pd.merge(df_students, df_marks, on="Student_ID",how="outer")

   Student_ID  Name  Marks
0           1  Amit    NaN
1           2  Ravi   85.0
2           3  Sita   90.0
3           4  Neha   75.0
4           5   NaN   60.0

5. Perform a cross merge between df_students and df_courses(CROSS JOIN) and display the result.

In [14]:
pd.merge(df_students, df_courses, how="cross")

    Student_ID_x  Name  Student_ID_y   Course
0              1  Amit             1     Math
1              1  Amit             2  Science
2              1  Amit             3  English
3              2  Ravi             1     Math
4              2  Ravi             2  Science
5              2  Ravi             3  English
6              3  Sita             1     Math
7              3  Sita             2  Science
8              3  Sita             3  English
9              4  Neha             1     Math
10             4  Neha             2  Science
11             4  Neha             3  English

6. Perform an inner merge between df_students and df_courses, then merge the result with df_marks (INNER JOIN ) and display the result.

In [16]:
inner_join=pd.merge(df_students, df_courses, on="Student_ID", how="inner")

In [19]:
result=pd.merge(inner_join,df_marks,how="inner")
result

   Student_ID  Name   Course  Marks
0           2  Ravi  Science     85
1           3  Sita  English     90

7. Perform a left merge between df_students and df_marks, then display students who have no marks (LEFT JOIN + CONDITION) and display the result.

In [22]:
marks=pd.merge(df_students, df_marks, on="Student_ID", how="left")
marks

   Student_ID  Name  Marks
0           1  Amit    NaN
1           2  Ravi   85.0
2           3  Sita   90.0
3           4  Neha   75.0

In [26]:

marks_no = marks[marks["Marks"].isnull()]

print(marks_no)

   Student_ID  Name  Marks
0           1  Amit    NaN

8.Perform a right merge between df_students and df_marks, then display records where student details are missing (RIGHT JOIN + FILTER)and display the result.

In [31]:
right_merge = pd.merge(df_students, df_marks, on="Student_ID", how="right")
missing_values = right_merge[right_merge["Name"].isnull()]
print(missing_values)

   Student_ID Name  Marks
3           5  NaN     60

9. OUTER JOIN + IDENTIFY
Perform an outer merge between df_students and df_marks, and identify:
only students
only marks
matching records   #Hint: indicator=True

In [34]:
outer_merge = pd.merge(df_students, df_marks, on="Student_ID", how="outer", indicator=True)

print(outer_merge)

   Student_ID  Name  Marks      _merge
0           1  Amit    NaN   left_only
1           2  Ravi   85.0        both
2           3  Sita   90.0        both
3           4  Neha   75.0        both
4           5   NaN   60.0  right_only

10. Perform a cross merge between df_students and df_courses, then count the total number of combinations generated (CROSS JOIN )and display the result.

In [39]:
merge=pd.merge(df_students,df_courses,how="cross")
print(len(merge))

12